version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: garden_postgres
    environment:
      POSTGRES_DB: garden_db
      POSTGRES_USER: garden_user
      POSTGRES_PASSWORD: garden_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - garden_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: garden_backend
    environment:
      DATABASE_URL: postgresql://garden_user:garden_password@postgres:5432/garden_db
      SECRET_KEY: your-secret-key-here
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - garden_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: garden_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - garden_network
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

volumes:
  postgres_data:

networks:
  garden_network:
    driver: bridge