# ======================================
# Garden システム Prometheus 監視メトリクス強化
# サイクル2: 100%完成レベル品質達成
# ======================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'garden-production'
    environment: 'production'

# アラートルール設定
rule_files:
  - "garden_alerts.yml"
  - "security_alerts.yml"
  - "performance_alerts.yml"

# Alertmanager設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Garden API サーバー監視
  - job_name: 'garden-api'
    static_configs:
      - targets: ['garden-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'garden-api'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_request_duration_seconds.*'
        target_label: __name__
        replacement: 'garden_${1}'

  # PostgreSQL データベース監視
  - job_name: 'garden-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      collect[]:
        - 'pg_stat_database'
        - 'pg_stat_user_tables'
        - 'pg_stat_activity'
        - 'pg_locks'
        - 'pg_replication'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'garden-postgres'

  # Nginx リバースプロキシ監視
  - job_name: 'garden-nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Node システムメトリクス監視
  - job_name: 'garden-node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'garden-production-server'

  # Redis キャッシュ監視
  - job_name: 'garden-redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # カスタムアプリケーションメトリクス
  - job_name: 'garden-custom-metrics'
    static_configs:
      - targets: ['garden-api:8000']
    metrics_path: '/custom-metrics'
    scrape_interval: 30s
    params:
      module: ['garden_business_metrics']

  # セキュリティメトリクス専用
  - job_name: 'garden-security'
    static_configs:
      - targets: ['garden-api:8000']
    metrics_path: '/security-metrics'
    scrape_interval: 60s
    params:
      module: ['security_monitoring']

  # パフォーマンステスト監視
  - job_name: 'garden-performance'
    static_configs:
      - targets: ['garden-api:8000']
    metrics_path: '/performance-metrics'
    scrape_interval: 120s
    honor_labels: true

# 高度な設定
remote_write:
  - url: "https://prometheus-remote-write.garden-dx.com/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 10
    metadata_config:
      send: true
      send_interval: 30s

# ストレージ設定
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    min-block-duration: 2h
    max-block-duration: 25h
    no-lockfile: false
    wal-compression: true