name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # テストとビルド
  test-and-build:
    runs-on: ubuntu-latest
    name: Test and Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Run linter
        working-directory: ./app
        run: npm run lint:check
        continue-on-error: true

      - name: Run type check
        working-directory: ./app
        run: npm run typecheck
        continue-on-error: true

      - name: Run tests
        working-directory: ./app
        run: npm test -- --watchAll=false --passWithNoTests
        env:
          CI: true

      - name: Build application
        working-directory: ./app
        run: CI=false npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          REACT_APP_DEMO_MODE: true
          REACT_APP_ENVIRONMENT: production

  # Vercelへのデプロイ
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./